server {
    listen 80;
    server_name _;

    # ── Frontend estático ──────────────────────
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # ── Proxy WebSocket terminal → backend ────
    location /terminal {
        proxy_pass         http://forge-backend:3000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       $host;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    # ── Proxy API REST → backend ──────────────
    location /api/ {
        proxy_pass       http://forge-backend:3000;
        proxy_set_header Host $host;
    }

    # ── Proxy Kali API → kali-api ─────────────
    location /kali-api/ {
        proxy_pass       http://forge-kali-api:4000/api/;
        proxy_set_header Host $host;
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }

    # ── Proxy noVNC → contenedor Kali ────────
    location /novnc/ {
        proxy_pass         http://forge-kali:6080/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       $host;
    }
}
