"""
forge.config
────────────
Persistent Forge configuration, stored in <project>/.forge/config.json:

{
  "kali_user": "hacker",
  "network_mode": "bridge" | "nat" | "host" | "none",
  "timezone": "America/Mexico_City",
  "lang": "en_US.UTF-8",
  "vnc_resolution": "1280x800",
  "shared_folders": [
      {"host": "/abs/path", "container": "/home/hacker/shared/x", "ro": false}
  ],
  "last_mode": "full"
}

The password is NEVER stored in config.json: it lives only in the project's .env
(with 600 permissions), just like any normal docker-compose.
All functions receive a `ForgeContext` (see forge.paths) that already
knows where `.forge/` lives for this particular project.
"""

from __future__ import annotations

import json
import os
import stat
from dataclasses import asdict, dataclass, field

from .paths import ForgeContext

DEFAULT_NETWORK_MODE = "bridge"
DEFAULT_TIMEZONE = "America/Chicago"
DEFAULT_VNC_RES = "1280x800"

VALID_NETWORK_MODES = ("bridge", "nat", "host", "none")


@dataclass
class SharedFolder:
    host: str
    container: str
    ro: bool = False


@dataclass
class ForgeConfig:
    kali_user: str = "hacker"
    network_mode: str = DEFAULT_NETWORK_MODE
    timezone: str = DEFAULT_TIMEZONE
    lang: str = ""
    vnc_resolution: str = DEFAULT_VNC_RES
    shared_folders: list[dict] = field(default_factory=list)
    last_mode: str = "full"
    installed: bool = False

    # ── (de)serialization ──────────────────────────────────────────
    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "ForgeConfig":
        known = {f: data.get(f) for f in cls.__dataclass_fields__ if f in data}
        return cls(**{**cls().to_dict(), **known})

    def add_shared_folder(self, host: str, container: str, ro: bool = False) -> None:
        entry = {"host": host, "container": container, "ro": ro}
        # avoid duplicates by host path
        self.shared_folders = [sf for sf in self.shared_folders if sf["host"] != host]
        self.shared_folders.append(entry)


def is_installed(ctx: ForgeContext) -> bool:
    return ctx.config_file.is_file()


def load(ctx: ForgeContext) -> ForgeConfig:
    if not ctx.config_file.is_file():
        raise SystemExit(
            "Forge is not installed in this project yet. Run first: forge install"
        )
    data = json.loads(ctx.config_file.read_text())
    return ForgeConfig.from_dict(data)


def save(ctx: ForgeContext, cfg: ForgeConfig) -> None:
    ctx.forge_home.mkdir(parents=True, exist_ok=True)
    ctx.config_file.write_text(json.dumps(cfg.to_dict(), indent=2, ensure_ascii=False))
    ctx.config_file.chmod(0o600)


# ── project .env (docker-compose reads it automatically) ─────────
def write_env_file(ctx: ForgeContext, cfg: ForgeConfig, password: str):
    lines = [
        "# Automatically generated by `forge install` — do not share this file",
        f"KALI_USER={cfg.kali_user}",
        f"KALI_PASSWORD={password}",
        f"TIME_ZONE={cfg.timezone}",
        f"VNC_RESOLUTION={cfg.vnc_resolution}",
    ]
    if cfg.lang:
        lines.append(f"LANG={cfg.lang}")
    ctx.env_file.write_text("\n".join(lines) + "\n")
    # Contains the password: restricted permissions
    os.chmod(ctx.env_file, stat.S_IRUSR | stat.S_IWUSR)
    return ctx.env_file


def read_env_password(ctx: ForgeContext) -> str | None:
    if not ctx.env_file.is_file():
        return None
    for line in ctx.env_file.read_text().splitlines():
        if line.startswith("KALI_PASSWORD="):
            return line.split("=", 1)[1]
    return None
